#!/bin/bash
# ./publish-post docs/_posts/<post_file>

post_path="$1"

if ! grep -q -P 'published:\s*false' "$post_path"; then
    echo "Already published"
    exit 1
fi

today=`date -I`
timestamp=`date +"%Y-%m-%d %H:%M:%S %z"`

new_post_path=`echo "$post_path" | perl -pe "s([/]\d{4}-\d{2}-\d{2}-)(/$today-)"`
mv $post_path $new_post_path

perl -pi -e 's/published:\s*false/published: true/' $new_post_path
perl -pi -e "s/date:(\s*).*/'date:' . \$1 . '$timestamp'/e" $new_post_path
