#!/bin/bash
# ./publish-post docs/_posts/<post_file>

PATH=$PATH:./vendor/docopts
eval "$(docopts -V - -h - : "$@" <<EOF
Usage: publish-post [options] <post_path>

Options:
      --keep-date  Do not update the post date.
      --help       Show help options.
      --version    Print program version.
----
publish-post 0.1.0
EOF
)"

if ! grep -q -P 'published:\s*false' "$post_path"; then
    echo "Already published"
    exit 1
fi

today=`date -I`
timestamp=`date +"%Y-%m-%d %H:%M:%S %z"`

new_post_path="$post_path"
if ! $keep_date; then
    new_post_path=`echo "$post_path" | perl -pe "s([/]\d{4}-\d{2}-\d{2}-)(/$today-)"`
fi

if [ "$post_path" != "$new_post_path" ]; then
    mv $post_path $new_post_path
fi

perl -pi -e 's/published:\s*false/published: true/' $new_post_path
if ! $keep_date; then
    perl -pi -e "s/date:(\s*).*/'date:' . \$1 . '$timestamp'/e" $new_post_path
fi
